server:
  port: 8081
  servlet:
    context-path: /orders
spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://postgres:5432/STORAGE
    username: Kaindall
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://app-discovery:8070/eureka/
  instance:
    prefer-ip-address: true
kafka:
  url: kafka:9092
  producer:
    topic: movement-qeue
  consumer:
    topic: movement-result
    group-id: movements-consumer-1
clients:
  movements:
    url: http://products:8080
