spring:
  application:
    name: products
  datasource:
    url: jdbc:mysql://mysql:3306/STORAGE?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: Kaindall
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi-ui
kafka:
  url: kafka:9092
  producer:
    topic: movement-result
  consumer:
    topic: movement
    group-id: products-consumer-1