server:
  port: 8082
  servlet:
    context-path: /products
spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://postgres:5432/STORAGE
    username: Kaindall
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi-ui
eureka:
  client:
    service-url:
      defaultZone: http://app-discovery:8070/eureka/
  instance:
    prefer-ip-address: false
    hostname: app-products
kafka:
  url: kafka:9092
  producer:
    topic: movement-result
  consumer:
    topic: movement
    group-id: products-consumer-1