spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
      server:
        webflux:
          routes:
            - id: test
              uri: https://httpbin.org
              predicates:
                - Path=/get
            - id: app-keycloak
              uri: http://keycloak:9091
              predicates:
                - Path=/oauth/token
              filters:
                - RewritePath=/oauth/token,/realms/dev/protocol/openid-connect/token
            - id: app-discover
              uri: http://app-discovery:8070
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/
            - id: discovery-static
              uri: http://app-discovery:8070
              predicates:
                - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9091/realms/dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://kaindall:123456@app-discovery:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: false
      hostname: app-gateway
logging:
  level:
    ROOT: DEBUG