server:
  port: 8083
  servlet:
    context-path: /notifications
eureka:
  client:
    service-url:
      defaultZone: http://app-discovery:8070/eureka/
  instance:
    prefer-ip-address: false
    hostname: app-notifications
kafka:
  url: kafka:9092
  consumer:
    topic: notification-queue
    group-id: notification-consumer-1
twilio:
  account:
    number:
    sid:
    token:
spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    origin: teste@email.com
    username:
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
