server:
  port: 8083
  servlet:
    context-path: /notifications
spring:
  application:
    name: notifications
eureka:
  client:
    service-url:
      defaultZone: http://app-discovery:8070/eureka/
  instance:
    prefer-ip-address: false
    hostname: app-notifications
#kafka:
#  url: kafka:9092
#  consumer:
#    topic: notification
#    group-id: notifications-consumer-1